apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  labels:
    app.kubernetes.io/name: postgres-target
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  postgresql.conf: |
    listen_addresses = '*'
    port = 5432
    max_connections = {{ .Values.postgres.maxConnections }}
    shared_buffers = '{{ .Values.postgres.sharedBuffers }}'
