apiVersion: v1
kind: Service
metadata:
  name: fake-pagerduty
  labels:
    app.kubernetes.io/name: fake-pagerduty
spec:
  selector:
    app.kubernetes.io/name: fake-pagerduty
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 8080
