apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-scenario-overrides
  namespace: kube-system
data:
  Corefile.override: |
    example.com:53 {
        errors
        template IN A checkout.example.com {
            rcode NXDOMAIN
        }
        forward . /etc/resolv.conf
    }
